name: CD - Build and push docker image

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths: [ 'hangman-api/**' ]

jobs:
  delivery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Docker login into Docker Hub
        uses: docker/login-action@v3
        with:
          username: jtrillo
          password: ${{ secrets.DOCKER_PASSWORD }}