name: CD - Build and push docker image

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths: [ 'hangman-api/**' ]

jobs:
  delivery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Docker login into Docker Hub
        uses: docker/login-action@v3
        with:
          username: jtrillo
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./hangman-api
          push: true
          tags: jtrillo/hangman-api-lemon6-gh:latest
          file: ./hangman-api/Dockerfile
