name: CI - Using Artifacts

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
    paths: [ 'hangman-api/**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node version
        uses: actions/setup-node@v6
        with:
          node-version: 20
      - name: Build and test
        working-directory: ./hangman-api
        run: |
          npm ci
          npm run build --if-present
      - name: Upload node modules as artifact
        uses: actions/upload-artifact@v6
        with:
          name: dependencies
          path: hangman-api/node_modules
          include-hidden-files: true
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node version
        uses: actions/setup-node@v6
        with:
          node-version: 20
      - name: Download node modules
        uses: actions/download-artifact@v7
        with:
          name: dependencies
          path: hangman-api/node_modules
      - name: Build and test
        working-directory: ./hangman-api
        run: |
          chmod -R +x node_modules
          npm run test
  last:
    runs-on: ubuntu-latest
    needs: test
    # if: ${{ always() }}
    steps:
      - name: Bye
        run: echo "Bye!"