name: CI - using matrix

on:
  push:
    branches: [ master ]
    paths: [ 'hangman-api/**' ]
  pull_request:
    branches: [ master ]
    paths: [ 'hangman-api/**' ]

jobs:
  build-test:
    strategy:
      matrix:
        node-version: [16, 18, 20]
        os: [ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node version
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build and test
        working-directory: ./hangman-api
        run: |
          npm ci
          npm run build --if-present
          npm test