name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths: [ 'hangman-api/**' ]

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Audit Docker version
        run: docker -v
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v6
  #     - name: Setup Node version
  #       uses: actions/setup-node@v6
  #       with:
  #         node-version: 20
  #         cache: 'npm'
  #         cache-dependency-path: hangman-api/package-lock.json
  #     - name: Build and test
  #       working-directory: ./hangman-api
  #       run: |
  #         npm ci
  #         npm run build --if-present
  # test:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v6
  #     - name: Setup Node version
  #       uses: actions/setup-node@v6
  #       with:
  #         node-version: 20
  #     - name: Build and test
  #       working-directory: ./hangman-api
  #       run: |
  #         npm ci
  #         npm run test
  # last:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   # if: ${{ always() }}
  #   steps:
  #     - name: Bye
  #       run: echo "Bye!"